name: Enhancement / Feature request
description: Request for a feature to include with the extension.
title: "[ Feature Request ] (Title)"
labels: enhancement

body:
  - id: enhancement
    type: textarea
    attributes:
      label: Describe the enhancement & expected behavior.
    validations:
      required: true