name: Issues with other Extensions (3rd-Party Bug)
description: Create a report that has to do with another extension.
title: "[ 3rd-Party Bug ] (Title)"
labels: 3rd-party, bug

body:
  - id: problem
    type: textarea
    attributes:
      label: A clear and concise description of what the bug is.
    validations:
      required: true
  - id: screenshots
    type: textarea
    attributes:
      label: If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - id: script-or-extension
    type: textarea
    attributes:
      label: The userscript or extension that makes this issue occur.
    validations:
      required: true
  - id: expected-behavior
    type: textarea
    attributes:
      label: What should actually happen instead of the issue.
    validations:
      required: true
  - id: reproduce
    type: textarea
    attributes:
      label: Steps to reproduce the behavior.
    validations:
      required: true
  - id: config
    type: textarea
    attributes:
      label: OldTwitch settings. (TBA)
    validations:
      required: true
  - id: browser-info
    type: textarea
    attributes:
      label: Browser & Extension information (& video if shown).
    validations:
      required: true